# Generated by Django 3.1.4 on 2021-01-19 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0021_auto_20210119_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Добавлено в избранное (раз)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images', verbose_name='Внешний вид'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(related_name='recipes', through='recipe.RecipeIngridient', to='recipe.Ingridient', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, related_name='purchased_recipes', through='recipe.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Покупатели'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(to='recipe.Tag', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
