# Generated by Django 3.1.4 on 2021-01-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0024_auto_20210119_1511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followrecipe',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='followuser',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='followrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_n_recipe_fav_unique'),
        ),
        migrations.AddConstraint(
            model_name='followuser',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='user_n_author_follow_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user_n_recipe_cart_unique'),
        ),
    ]
