# Generated by Django 3.1.4 on 2021-01-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0026_auto_20210121_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingridient',
            options={'verbose_name': 'Ингридиент рецепта', 'verbose_name_plural': 'Ингридиенты рецептов'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
