# Generated by Django 3.1.4 on 2021-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0027_auto_20210122_1140'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingridient',
            constraint=models.UniqueConstraint(fields=('title', 'measurement_unit'), name='title_n_unit_ingredient_unique'),
        ),
    ]
