version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: timurhamzin/foodgram
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./static_root:/foodgram/static_root/
      - ./media:/foodgram/media/
    command: gunicorn recipes.wsgi:application --bind 0.0.0.0:8000
  nginx:
    image: nginx:1.19.3
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./static_root:/foodgram/static_root/
      - ./media:/foodgram/media/
    ports:
      - 80:80
    links:
      - web:web
    depends_on:
      - web
