name: yamdb_final workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 --ignore=E501,F401,F541,F403,F405 --exclude=venv


  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push app container to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: timurhamzin/foodgram


  deploy:
   runs-on: ubuntu-latest
   needs: build_and_push_to_docker_hub
   if:
     contains('
     refs/heads/master
     refs/heads/main
     ', github.ref)
   steps:
   - uses: actions/checkout@master 
   - name: copy docker-compose.yaml file to remote 
     uses: appleboy/scp-action@master 
     with: 
       host: 130.193.43.193
       username: yc-user
       key: ${{ secrets.SSH_KEY_YACLOUD_PRAKTIKUM }}
       passphrase: ${{ secrets.SSH_PASSPHRASE_YACLOUD_PRAKTIKUM }}
       source: "./docker-compose.yaml,./docker-compose.override.yaml,./.env,./nginx_default.conf"
       target: "./"
   - name: executing remote ssh commands to deploy
     uses: appleboy/ssh-action@master
     with:
       host: 130.193.43.193
       username: yc-user
       key: ${{ secrets.SSH_KEY_YACLOUD_PRAKTIKUM }}
       passphrase: ${{ secrets.SSH_PASSPHRASE_YACLOUD_PRAKTIKUM }}
       script: |
         docker-compose down
         docker-compose pull
         docker-compose up -d

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
